# DropConfirm ${project.version} main config file.

check-for-updates: true

language: en
available_languages:
  - en
  - es

data-options:
  auto-save-data: true
  data-save-delay: 12000
  # 1200 Ticks = 1 Minute

drop-options:
  drop-confirm-per-item: true
  drop-confirm-message: true
  reset-confirm-on-pickup: true
  drop-timer: 10

item-list-enabled: false
item-list:
  normal-items:
  # - ALL
    - DIAMOND_AXE
    - DIAMOND_SWORD
    - STONE
  custom-items:
    example_item:
      material: IRON_SWORD
      name: '&aExample Item'