# DropConfirm 1.0.0 main config file.

language: en
languages:
  - en
  - es

general-options:
  save-playerdata: true
  drop-confirm-per-item: true
  drop-confirm-message: true
  timer: 10

item-list-enabled: false
item-list:
  normal-items:
  # - ALL
    - DIAMOND_AXE
    - DIAMOND_SWORD
    - STONE
  custom-items:
    example:
      material: IRON_SWORD
      name: '&aExample Name'