name: DropConfirm
version: 1.0.0
main: me.nickax.dropconfirm.DropConfirm
author: Nickax
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  dropconfirm:
    description: show the command list.